/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Liveness */
        get: operations["get_liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Readiness */
        get: operations["get_readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current User */
        get: operations["get_current_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account */
        get: operations["get_account"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Account Usage
         * @description One row per act, newest first, with its 预扣 folded into it.
         *
         *     A 结算 is never its own row. On its own it reads as 额度 arriving from
         *     nowhere; against the 预扣 it corrects, it is the explanation for a number
         *     that moved and moved back — which is the whole reason this page shows
         *     the two together.
         */
        get: operations["list_account_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task */
        get: operations["get_task"];
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task"];
        options?: never;
        head?: never;
        /** Rename Task */
        patch: operations["rename_task"];
        trace?: never;
    };
    "/tasks/{task_id}/current-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Task Version */
        get: operations["get_current_task_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Task Source */
        post: operations["prepare_task_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Task Creation */
        post: operations["confirm_task_creation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/pasted-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Pasted Source */
        post: operations["create_pasted_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/pasted-sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Pasted Source */
        patch: operations["edit_pasted_source"];
        trace?: never;
    };
    "/task-creation/sessions/{client_session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Creation Session */
        get: operations["get_task_creation_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Task Creation Source */
        delete: operations["delete_task_creation_source"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/url-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Url Source */
        post: operations["create_url_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/url-sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Url Source */
        get: operations["get_url_source"];
        /** Replace Url Source */
        put: operations["replace_url_source"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/url-sources/{source_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Url Source */
        post: operations["retry_url_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/url-sources/{source_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Url Source Content */
        patch: operations["edit_url_source_content"];
        trace?: never;
    };
    "/executions/{execution_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution */
        get: operations["get_execution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/executions/{execution_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Execution */
        post: operations["cancel_execution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/file-sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create File Source */
        post: operations["create_file_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/file-sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get File Source */
        get: operations["get_file_source"];
        /** Replace File Source */
        put: operations["replace_file_source"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/file-sources/{source_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry File Source */
        post: operations["retry_file_source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task-creation/file-sources/{source_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit File Source Content */
        patch: operations["edit_file_source_content"];
        trace?: never;
    };
    "/source-revisions/{source_revision_id}/zhiyan-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Zhiyan Run */
        post: operations["start_zhiyan_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-revisions/{source_revision_id}/zhiyan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Zhiyan State */
        get: operations["get_zhiyan_state"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/versions/{version_id}/zhiyan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Version Zhiyan */
        get: operations["get_task_version_zhiyan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/zhiyan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Zhiyan
         * @description Every 知言 run of the task's current 任务版本, and whether 立言 may open.
         */
        get: operations["get_task_zhiyan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_task_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/source-edit-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Edit Session */
        post: operations["create_source_edit_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-edit-sessions/{edit_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Edit Session */
        post: operations["discard_source_edit_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-edit-sessions/{edit_id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Edit Session */
        post: operations["save_source_edit_session"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/versions/{version_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Version */
        post: operations["restore_task_version"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/liyan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Liyan */
        get: operations["get_task_liyan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/liyan-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Liyan Run */
        post: operations["start_liyan_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/liyan-revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Liyan Revision */
        post: operations["save_liyan_revision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/liyan-revisions/{revision_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Liyan Revision */
        post: operations["restore_liyan_revision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publication/targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Publication Targets */
        get: operations["list_publication_targets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publication/eligible-articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eligible Articles */
        get: operations["list_eligible_articles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publication/publish-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Publish Tasks */
        get: operations["list_publish_tasks"];
        put?: never;
        /** Confirm Publication */
        post: operations["confirm_publication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publication/publish-tasks/{publish_task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Publication
         * @description Send the snapshot again, and only the snapshot.
         *
         *     Retrying reads nothing the user could have changed since: the 发布任务
         *     already holds the title, body, author, and target this attempt will use.
         *     A newer article therefore cannot ride out on a retry — publishing it is
         *     a new confirmation, with the warning that goes with one.
         */
        post: operations["retry_publication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/publication/publish-tasks/{publish_task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Publish Task */
        get: operations["get_publish_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountResponse */
        AccountResponse: {
            /** Remaining Credits */
            remaining_credits: number;
            /** Is Paying User */
            is_paying_user: boolean;
        };
        /** @enum {string} */
        ActivityStatus: "running" | "done" | "failed" | "none";
        /** Body_create_file_source */
        Body_create_file_source: {
            /** Client Session Id */
            client_session_id: string;
            /** Client Source Id */
            client_source_id: string;
            /** File */
            file: string;
        };
        /** Body_replace_file_source */
        Body_replace_file_source: {
            /** File */
            file: string;
        };
        /** ConfirmPublicationRequest */
        ConfirmPublicationRequest: {
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Revision Id
             * Format: uuid
             */
            revision_id: string;
            /** Target Key */
            target_key: string;
            /** Author */
            author: string;
            /** Working Copy Hash */
            working_copy_hash?: string | null;
            /**
             * Acknowledge Existing Preview
             * @default false
             */
            acknowledge_existing_preview: boolean;
        };
        /** ConfirmTaskRequest */
        ConfirmTaskRequest: {
            /** Idempotency Key */
            idempotency_key: string;
            source?: components["schemas"]["SourceInput"] | null;
            /** Client Session Id */
            client_session_id?: string | null;
            /** Source Ids */
            source_ids?: string[];
            /** Accepted Warning Versions */
            accepted_warning_versions?: {
                [key: string]: number;
            };
        };
        /** ConfirmTaskResponse */
        ConfirmTaskResponse: {
            task: components["schemas"]["TaskSummary"];
            source_revision: components["schemas"]["SourceRevisionResponse"];
            /** Source Revisions */
            source_revisions: components["schemas"]["SourceRevisionResponse"][];
        };
        /** CreatePastedSourceRequest */
        CreatePastedSourceRequest: {
            /** Client Session Id */
            client_session_id: string;
            /** Client Source Id */
            client_source_id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Provenance */
            provenance?: string | null;
        };
        /** CreateUrlSourceRequest */
        CreateUrlSourceRequest: {
            /** Client Session Id */
            client_session_id: string;
            /** Client Source Id */
            client_source_id: string;
            /** Url */
            url: string;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
        };
        /** DeleteTaskRequest */
        DeleteTaskRequest: {
            /**
             * Confirmed
             * @constant
             */
            confirmed: true;
        };
        /** EditPastedSourceRequest */
        EditPastedSourceRequest: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Provenance */
            provenance?: string | null;
        };
        /** EditSourceContentRequest */
        EditSourceContentRequest: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Provenance */
            provenance?: string | null;
        };
        /** EligibleArticleListResponse */
        EligibleArticleListResponse: {
            /** Items */
            items: components["schemas"]["EligibleArticleResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** EligibleArticleResponse */
        EligibleArticleResponse: {
            /** Task Id */
            task_id: string;
            /** Task Number */
            task_number: number;
            /** Task Display Name */
            task_display_name: string;
            /** Task Version Id */
            task_version_id: string;
            /** Revision Id */
            revision_id: string;
            /** Revision Number */
            revision_number: number;
            /** Title */
            title: string;
            /** Body Markdown */
            body_markdown: string;
            /** Content Hash */
            content_hash: string;
            /**
             * Saved At
             * Format: date-time
             */
            saved_at: string;
        };
        /** EvidenceItem */
        EvidenceItem: {
            id: components["schemas"]["Narrative"];
            title: components["schemas"]["Narrative"];
            url: components["schemas"]["Narrative"];
            explanation: components["schemas"]["Narrative"];
        };
        /** EvidenceSection */
        EvidenceSection: {
            /** Items */
            items: components["schemas"]["EvidenceItem"][];
            /** Empty State */
            empty_state: string | null;
        };
        /** ExecutionError */
        ExecutionError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ExecutionResponse */
        ExecutionResponse: {
            /** Id */
            id: string;
            /**
             * Operation
             * @enum {string}
             */
            operation: "fetch_url" | "parse_file" | "analyze_source" | "generate_article" | "publish_preview";
            status: components["schemas"]["ExecutionStatus"];
            /** Attempt */
            attempt: number;
            /** Input Version */
            input_version: number;
            /** Trace Id */
            trace_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Cancellation Requested At */
            cancellation_requested_at: string | null;
            /** Result Id */
            result_id: string | null;
            error: components["schemas"]["ExecutionError"] | null;
        };
        /** @enum {string} */
        ExecutionStatus: "queued" | "running" | "cancel_requested" | "cancelled" | "failed" | "stale" | "succeeded";
        /** FactItem */
        FactItem: {
            id: components["schemas"]["Narrative"];
            quote: components["schemas"]["Narrative"];
            claim: components["schemas"]["Narrative"];
            verdict: components["schemas"]["FactVerdict"];
            explanation: components["schemas"]["Narrative"];
            /** Evidence Ids */
            evidence_ids: string[];
        };
        /** FactSection */
        FactSection: {
            /** Items */
            items: components["schemas"]["FactItem"][];
            /** Empty State */
            empty_state: string | null;
        };
        /** @enum {string} */
        FactVerdict: "有证据支持" | "有证据反驳" | "部分准确" | "存在争议" | "暂无法核实";
        /** FileSourceCapabilities */
        FileSourceCapabilities: {
            /** Can Retry */
            can_retry: boolean;
            /** Can Replace */
            can_replace: boolean;
            /** Can Cancel */
            can_cancel: boolean;
        };
        /** FileSourceResponse */
        FileSourceResponse: {
            /** Id */
            id: string;
            /** Client Session Id */
            client_session_id: string;
            /** Client Source Id */
            client_source_id: string;
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Content Hash */
            content_hash: string;
            /** Size Bytes */
            size_bytes: number;
            /** Input Version */
            input_version: number;
            status: components["schemas"]["SourcePreparationStatus"];
            /** Title */
            title: string | null;
            /** Body */
            body: string | null;
            /** Provenance */
            provenance: string | null;
            /** Warnings */
            warnings: components["schemas"]["SourceWarning"][];
            failure: components["schemas"]["SourceFailure"] | null;
            active_execution: components["schemas"]["ExecutionResponse"] | null;
            capabilities: components["schemas"]["FileSourceCapabilities"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InstructionCapsule */
        InstructionCapsule: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "capsule";
            /**
             * Task Version Id
             * Format: uuid
             */
            task_version_id: string;
            /**
             * Report Id
             * Format: uuid
             */
            report_id: string;
            /** Item Id */
            item_id: string;
        };
        /** InstructionDocument */
        InstructionDocument: {
            /** Content */
            content?: components["schemas"]["InstructionPart"][];
        };
        InstructionPart: components["schemas"]["InstructionText"] | components["schemas"]["InstructionCapsule"];
        /** InstructionText */
        InstructionText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
        /** IntentItem */
        IntentItem: {
            id: components["schemas"]["Narrative"];
            quote: components["schemas"]["Narrative"];
            possible_intent: components["schemas"]["Narrative"];
            explanation: components["schemas"]["Narrative"];
        };
        /** IntentSection */
        IntentSection: {
            explicit_purpose: components["schemas"]["Narrative"];
            /** Items */
            items: components["schemas"]["IntentItem"][];
            target_audience: components["schemas"]["Narrative"];
            /** Expression Methods */
            expression_methods: string[];
            /** Empty State */
            empty_state: string | null;
        };
        /** KeyFinding */
        KeyFinding: {
            ref_id: components["schemas"]["Narrative"];
            text: components["schemas"]["Narrative"];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "alive";
        };
        /** LiyanCapabilities */
        LiyanCapabilities: {
            /** Can Generate */
            can_generate: boolean;
            /** Unavailable Reason */
            unavailable_reason: string | null;
        };
        /** LiyanResultResponse */
        LiyanResultResponse: {
            /** Id */
            id: string;
            /** Execution Id */
            execution_id: string;
            /** Task Version Id */
            task_version_id: string;
            /** Title */
            title: string;
            /** Body Markdown */
            body_markdown: string;
            instruction: components["schemas"]["InstructionDocument"];
            /** Prompt Version */
            prompt_version: string;
            /** Model */
            model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LiyanRetryState */
        LiyanRetryState: {
            /** Allowed */
            allowed: boolean;
            /** Remaining */
            remaining: number;
            /** Allowed At */
            allowed_at: string | null;
        };
        /** LiyanRevisionHistoryResponse */
        LiyanRevisionHistoryResponse: {
            current: components["schemas"]["LiyanRevisionResponse"] | null;
            /** Historical */
            historical: components["schemas"]["LiyanRevisionResponse"][];
            /**
             * Historical Limit
             * @default 3
             */
            historical_limit: number;
        };
        /** LiyanRevisionResponse */
        LiyanRevisionResponse: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /** Task Version Id */
            task_version_id: string;
            /** Title */
            title: string;
            /** Body Markdown */
            body_markdown: string;
            /** Content Hash */
            content_hash: string;
            /** Base Revision Id */
            base_revision_id: string | null;
            /** Restored From Revision Id */
            restored_from_revision_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LiyanRunCapabilities */
        LiyanRunCapabilities: {
            /** Can Generate */
            can_generate: boolean;
            /** Can Cancel */
            can_cancel: boolean;
            /** Can Save */
            can_save: boolean;
            /** Publishable Revision Id */
            publishable_revision_id: string | null;
            /** Publication Unavailable Reason */
            publication_unavailable_reason: string | null;
            retry: components["schemas"]["LiyanRetryState"];
            /** Unavailable Reason */
            unavailable_reason: string | null;
        };
        /** LiyanRunRequestResponse */
        LiyanRunRequestResponse: {
            instruction: components["schemas"]["InstructionDocument"];
            working_copy: components["schemas"]["WorkingCopyInput"] | null;
        };
        /** LiyanStateResponse */
        LiyanStateResponse: {
            /** Task Id */
            task_id: string;
            /** Task Version Id */
            task_version_id: string;
            status: components["schemas"]["LiyanStatus"];
            execution: components["schemas"]["ExecutionResponse"] | null;
            result: components["schemas"]["LiyanResultResponse"] | null;
            request: components["schemas"]["LiyanRunRequestResponse"] | null;
            revisions: components["schemas"]["LiyanRevisionHistoryResponse"];
            capabilities: components["schemas"]["LiyanRunCapabilities"];
        };
        /** @enum {string} */
        LiyanStatus: "absent" | "running" | "cancelled" | "failed" | "succeeded";
        /** LogicItem */
        LogicItem: {
            id: components["schemas"]["Narrative"];
            quote: components["schemas"]["Narrative"];
            judgment: components["schemas"]["Narrative"];
            explanation: components["schemas"]["Narrative"];
            /** Related Ids */
            related_ids: string[];
        };
        /** LogicSection */
        LogicSection: {
            argument_chain: components["schemas"]["Narrative"];
            /** Items */
            items: components["schemas"]["LogicItem"][];
            /** Empty State */
            empty_state: string | null;
        };
        Narrative: string;
        /** @enum {string} */
        ObjectStorageState: "ready" | "unconfigured" | "unreachable";
        /** OverviewSection */
        OverviewSection: {
            content_summary: components["schemas"]["Narrative"];
            fact_check_summary: components["schemas"]["Narrative"];
            /** Key Findings */
            key_findings: components["schemas"]["KeyFinding"][];
            reading_note: components["schemas"]["Narrative"];
        };
        /** PreparationWarning */
        PreparationWarning: {
            /**
             * Code
             * @enum {string}
             */
            code: "short_body" | "missing_provenance";
            /** Message */
            message: string;
        };
        /** PrepareSourceResponse */
        PrepareSourceResponse: {
            source: components["schemas"]["PreparedSource"];
            /** Warnings */
            warnings: components["schemas"]["PreparationWarning"][];
            /**
             * Can Confirm
             * @default true
             * @constant
             */
            can_confirm: true;
        };
        /** PreparedSource */
        PreparedSource: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Provenance */
            provenance: string | null;
        };
        /** PublicationTargetListResponse */
        PublicationTargetListResponse: {
            /** Items */
            items: components["schemas"]["PublicationTargetResponse"][];
        };
        /** PublicationTargetResponse */
        PublicationTargetResponse: {
            /** Key */
            key: string;
            /** Platform */
            platform: string;
            /** Display Name */
            display_name: string;
            /** Site Url */
            site_url: string;
        };
        /** PublishTaskListResponse */
        PublishTaskListResponse: {
            /** Items */
            items: components["schemas"]["PublishTaskResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PublishTaskResponse */
        PublishTaskResponse: {
            /** Id */
            id: string;
            status: components["schemas"]["PublishTaskStatus"];
            /** Task Id */
            task_id: string;
            /** Task Display Name */
            task_display_name: string;
            /** Task Version Id */
            task_version_id: string;
            /** Revision Id */
            revision_id: string;
            /** Revision Number */
            revision_number: number;
            /** Title */
            title: string;
            /** Body Markdown */
            body_markdown: string;
            target: components["schemas"]["PublicationTargetResponse"];
            /** Author */
            author: string;
            /** Post Type */
            post_type: string;
            /** Requested Status */
            requested_status: string;
            /** Preview Url */
            preview_url: string | null;
            /** External Slug */
            external_slug: string | null;
            /** External Version */
            external_version: string | null;
            /** Response Evidence */
            response_evidence: {
                [key: string]: unknown;
            } | null;
            /** Failure Message */
            failure_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at: string | null;
            execution: components["schemas"]["ExecutionResponse"] | null;
            /** Attempts */
            attempts: components["schemas"]["ExecutionResponse"][];
        };
        /** @enum {string} */
        PublishTaskStatus: "pending" | "succeeded" | "failed" | "outcome_unknown";
        /** ReadinessChecks */
        ReadinessChecks: {
            /**
             * Database
             * @enum {string}
             */
            database: "available" | "unavailable";
            /**
             * Queue
             * @enum {string}
             */
            queue: "available" | "unavailable";
            worker: components["schemas"]["WorkerState"];
            object_storage: components["schemas"]["ObjectStorageState"];
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
            checks: components["schemas"]["ReadinessChecks"];
        };
        /** RenameTaskRequest */
        RenameTaskRequest: {
            /** Display Name */
            display_name: string;
        };
        /** ReplaceUrlSourceRequest */
        ReplaceUrlSourceRequest: {
            /** Url */
            url: string;
        };
        /** RestoreLiyanRevisionRequest */
        RestoreLiyanRevisionRequest: {
            /** Idempotency Key */
            idempotency_key: string;
        };
        /** RestoreVersionRequest */
        RestoreVersionRequest: {
            /** Idempotency Key */
            idempotency_key: string;
        };
        /**
         * RetryPublicationRequest
         * @description Identity and consent — never content.
         *
         *     The 发布任务 already holds everything the attempt will send. A body that could
         *     name a title, an author, or a Revision would be a way to publish something
         *     newer under the word "retry".
         */
        RetryPublicationRequest: {
            /** Idempotency Key */
            idempotency_key: string;
            /**
             * Acknowledge Existing Preview
             * @default false
             */
            acknowledge_existing_preview: boolean;
        };
        /** SaveLiyanRevisionRequest */
        SaveLiyanRevisionRequest: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Base Revision Id */
            base_revision_id?: string | null;
            /** Title */
            title: string;
            /** Body Markdown */
            body_markdown: string;
        };
        /** SaveSourceEditRequest */
        SaveSourceEditRequest: {
            /** Idempotency Key */
            idempotency_key: string;
            /** Sources */
            sources: components["schemas"]["SaveSourceItem"][];
            /** Accepted Warning Versions */
            accepted_warning_versions?: {
                [key: string]: number;
            };
        };
        /** SaveSourceItem */
        SaveSourceItem: {
            /** Source Id */
            source_id?: string | null;
            /** Base Revision Id */
            base_revision_id?: string | null;
            /** Prepared Source Id */
            prepared_source_id?: string | null;
            content?: components["schemas"]["SourceInput"] | null;
        };
        /** SessionSourceCapabilities */
        SessionSourceCapabilities: {
            /** Can Retry */
            can_retry: boolean;
            /** Can Replace */
            can_replace: boolean;
            /** Can Edit */
            can_edit: boolean;
            /** Can Delete */
            can_delete: boolean;
            /** Can Cancel */
            can_cancel: boolean;
        };
        /** SessionSourceResponse */
        SessionSourceResponse: {
            /** Id */
            id: string;
            /** Client Source Id */
            client_source_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "pasted" | "url" | "file";
            /** Input Version */
            input_version: number;
            status: components["schemas"]["SourcePreparationStatus"];
            /** Title */
            title: string | null;
            /** Body */
            body: string | null;
            /** Provenance */
            provenance: string | null;
            /** Warnings */
            warnings: components["schemas"]["SourceWarning"][];
            failure: components["schemas"]["SourceFailure"] | null;
            active_execution: components["schemas"]["ExecutionResponse"] | null;
            capabilities: components["schemas"]["SessionSourceCapabilities"];
        };
        /** SourceEditSessionResponse */
        SourceEditSessionResponse: {
            /** Id */
            id: string;
            base_version: components["schemas"]["TaskVersionSnapshot"];
        };
        /** SourceFailure */
        SourceFailure: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** SourceInput */
        SourceInput: {
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Provenance */
            provenance?: string | null;
        };
        /** @enum {string} */
        SourcePreparationStatus: "processing" | "ready" | "warning" | "failure";
        /** SourceRevisionResponse */
        SourceRevisionResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Provenance */
            provenance: string | null;
        };
        /** SourceRevisionSummary */
        SourceRevisionSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Provenance */
            provenance: string | null;
        };
        /** SourceSection */
        SourceSection: {
            genre: components["schemas"]["Narrative"];
            provenance: components["schemas"]["Narrative"];
            completeness: components["schemas"]["Narrative"];
            note: components["schemas"]["Narrative"];
        };
        /** SourceWarning */
        SourceWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** StartLiyanRunRequest */
        StartLiyanRunRequest: {
            /** Idempotency Key */
            idempotency_key: string;
            instruction?: components["schemas"]["InstructionDocument"];
            working_copy?: components["schemas"]["WorkingCopyInput"] | null;
        };
        /** TaskCreationSessionResponse */
        TaskCreationSessionResponse: {
            /** Client Session Id */
            client_session_id: string;
            /** Source Count */
            source_count: number;
            /**
             * Max Sources
             * @default 3
             * @constant
             */
            max_sources: 3;
            /** Can Add */
            can_add: boolean;
            /** Can Confirm */
            can_confirm: boolean;
            /** Confirmation Disabled Reason */
            confirmation_disabled_reason: string | null;
            /** Sources */
            sources: components["schemas"]["SessionSourceResponse"][];
        };
        /** TaskListResponse */
        TaskListResponse: {
            /** Items */
            items: components["schemas"]["TaskSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** TaskSummary */
        TaskSummary: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /** Display Name */
            display_name: string;
            /** First Source Title */
            first_source_title: string;
            /** Additional Source Count */
            additional_source_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Activity At
             * Format: date-time
             */
            last_activity_at: string;
            /** Current Version Id */
            current_version_id: string;
            /** Current Version Number */
            current_version_number: number;
            /** Can Delete */
            can_delete: boolean;
            /** Delete Disabled Reason */
            delete_disabled_reason: string | null;
        };
        /** TaskVersionDetail */
        TaskVersionDetail: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Source Revisions */
            source_revisions: components["schemas"]["SourceRevisionSummary"][];
        };
        /** TaskVersionHistory */
        TaskVersionHistory: {
            /** Items */
            items: components["schemas"]["TaskVersionSnapshot"][];
            /**
             * Historical Limit
             * @default 3
             */
            historical_limit: number;
        };
        /** TaskVersionSnapshot */
        TaskVersionSnapshot: {
            /** Id */
            id: string;
            /** Number */
            number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Current */
            is_current: boolean;
            /** Sources */
            sources: components["schemas"]["VersionSource"][];
            capabilities: components["schemas"]["VersionCapabilities"];
        };
        /** TaskVersionZhiyanResponse */
        TaskVersionZhiyanResponse: {
            /** Task Id */
            task_id: string;
            /** Task Version Id */
            task_version_id: string;
            /** Task Version Number */
            task_version_number: number;
            /** Sources */
            sources: components["schemas"]["ZhiyanStateResponse"][];
            liyan: components["schemas"]["LiyanCapabilities"];
        };
        /** UrlSourceCapabilities */
        UrlSourceCapabilities: {
            /** Can Retry */
            can_retry: boolean;
            /** Can Replace */
            can_replace: boolean;
            /** Can Cancel */
            can_cancel: boolean;
        };
        /** UrlSourceResponse */
        UrlSourceResponse: {
            /** Id */
            id: string;
            /** Client Session Id */
            client_session_id: string;
            /** Client Source Id */
            client_source_id: string;
            /** Input Url */
            input_url: string;
            /** Normalized Url */
            normalized_url: string;
            /** Input Version */
            input_version: number;
            status: components["schemas"]["SourcePreparationStatus"];
            /** Title */
            title: string | null;
            /** Body */
            body: string | null;
            /** Provenance */
            provenance: string | null;
            /** Warnings */
            warnings: components["schemas"]["SourceWarning"][];
            failure: components["schemas"]["SourceFailure"] | null;
            active_execution: components["schemas"]["ExecutionResponse"] | null;
            capabilities: components["schemas"]["UrlSourceCapabilities"];
        };
        /** UsageEntry */
        UsageEntry: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Description */
            description: string;
            /** Task Id */
            task_id: string | null;
            status: components["schemas"]["ActivityStatus"];
            /** Amount */
            amount: number;
            /** Held */
            held: number | null;
            /**
             * Happened At
             * Format: date-time
             */
            happened_at: string;
        };
        /** UsageResponse */
        UsageResponse: {
            /** Entries */
            entries: components["schemas"]["UsageEntry"][];
            /** Has More */
            has_more: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionCapabilities */
        VersionCapabilities: {
            /** Can Edit */
            can_edit: boolean;
            /** Can Restore */
            can_restore: boolean;
            /** Unavailable Reason */
            unavailable_reason: string | null;
        };
        /** VersionSource */
        VersionSource: {
            /** Source Id */
            source_id: string;
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Provenance */
            provenance: string | null;
        };
        /** ViewpointItem */
        ViewpointItem: {
            id: components["schemas"]["Narrative"];
            quote: components["schemas"]["Narrative"];
            viewpoint: components["schemas"]["Narrative"];
            owner: components["schemas"]["Narrative"];
            analysis: components["schemas"]["Narrative"];
        };
        /** ViewpointSection */
        ViewpointSection: {
            /** Items */
            items: components["schemas"]["ViewpointItem"][];
            /** Empty State */
            empty_state: string | null;
        };
        /** @enum {string} */
        WorkerState: "beating" | "silent" | "unknown";
        /** WorkingCopyInput */
        WorkingCopyInput: {
            /** Title */
            title: string;
            /** Body Markdown */
            body_markdown: string;
        };
        /** ZhiyanCapabilities */
        ZhiyanCapabilities: {
            /** Can Start */
            can_start: boolean;
            /** Can Cancel */
            can_cancel: boolean;
            retry: components["schemas"]["ZhiyanRetryState"];
        };
        /**
         * ZhiyanReportDocument
         * @description The seven fixed sections of one 知言报告.
         */
        ZhiyanReportDocument: {
            overview: components["schemas"]["OverviewSection"];
            source: components["schemas"]["SourceSection"];
            facts: components["schemas"]["FactSection"];
            viewpoints: components["schemas"]["ViewpointSection"];
            logic: components["schemas"]["LogicSection"];
            intent: components["schemas"]["IntentSection"];
            evidence: components["schemas"]["EvidenceSection"];
        };
        /** ZhiyanReportResponse */
        ZhiyanReportResponse: {
            /** Id */
            id: string;
            /** Source Revision Id */
            source_revision_id: string;
            /** Prompt Version */
            prompt_version: string;
            /** Model */
            model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            document: components["schemas"]["ZhiyanReportDocument"];
        };
        /**
         * ZhiyanRetryState
         * @description Retry timing the server owns; the client only counts down to it.
         */
        ZhiyanRetryState: {
            /** Allowed */
            allowed: boolean;
            /** Remaining */
            remaining: number;
            /** Allowed At */
            allowed_at: string | null;
        };
        /** ZhiyanStateResponse */
        ZhiyanStateResponse: {
            /** Source Revision Id */
            source_revision_id: string;
            /** Source Title */
            source_title: string;
            status: components["schemas"]["ZhiyanStatus"];
            report: components["schemas"]["ZhiyanReportResponse"] | null;
            execution: components["schemas"]["ExecutionResponse"] | null;
            capabilities: components["schemas"]["ZhiyanCapabilities"];
        };
        /** @enum {string} */
        ZhiyanStatus: "absent" | "running" | "cancelled" | "failed" | "succeeded";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    get_readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    get_current_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    get_account: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
        };
    };
    list_account_usage: {
        parameters: {
            query?: {
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_task_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskVersionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_task_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrepareSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_task_creation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmTaskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pasted_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePastedSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_pasted_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditPastedSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_creation_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                client_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreationSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_creation_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_url_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUrlSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_url_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_url_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceUrlSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_url_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_url_source_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditSourceContentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UrlSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_execution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                execution_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_file_source: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_file_source"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_file_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_file_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_replace_file_source"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_file_source: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_file_source_content: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditSourceContentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSourceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_zhiyan_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZhiyanStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zhiyan_state: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_revision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZhiyanStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_version_zhiyan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskVersionZhiyanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_zhiyan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskVersionZhiyanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_task_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskVersionHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_edit_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceEditSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_source_edit_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_source_edit_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                edit_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveSourceEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskVersionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_task_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskVersionSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_liyan: {
        parameters: {
            query?: {
                working_copy_hash?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiyanStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_liyan_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartLiyanRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiyanStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_liyan_revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveLiyanRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiyanStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_liyan_revision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreLiyanRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiyanStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_publication_targets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationTargetListResponse"];
                };
            };
        };
    };
    list_eligible_articles: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibleArticleListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_publish_tasks: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishTaskListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_publication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmPublicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishTaskResponse"];
                };
            };
            /** @description Refused outright: nothing about this request can be made to work as sent. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The target may already hold an item for this 立言任务. Resend with `acknowledge_existing_preview` once the user has read the warning. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_publication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publish_task_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetryPublicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishTaskResponse"];
                };
            };
            /** @description Refused outright: nothing about this request can be made to work as sent. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The target may already hold an item for this 立言任务. Resend with `acknowledge_existing_preview` once the user has read the warning. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_publish_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publish_task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
